// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApvkwi1j9KJwt_oXQ-rwzyk3aGn1ZNGvs',
    appId: '1:130075632131:android:0429016fb26430ce6c6436',
    messagingSenderId: '130075632131',
    projectId: 'postman-appdev',
    storageBucket: 'postman-appdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY6vR4nTNOaIpOy7We2sxrP0s-SUHaFh0',
    appId: '1:130075632131:ios:2fea7d2e96926bae6c6436',
    messagingSenderId: '130075632131',
    projectId: 'postman-appdev',
    storageBucket: 'postman-appdev.firebasestorage.app',
    iosClientId:
        '130075632131-lstqvdi6luhbagqu19o8hue3hbba2rou.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY6vR4nTNOaIpOy7We2sxrP0s-SUHaFh0',
    appId: '1:130075632131:ios:2fea7d2e96926bae6c6436',
    messagingSenderId: '130075632131',
    projectId: 'postman-appdev',
    storageBucket: 'postman-appdev.firebasestorage.app',
    iosClientId:
        '130075632131-lstqvdi6luhbagqu19o8hue3hbba2rou.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterApp',
  );
}
